### ISSUE TITLE
Error: ModuleNotFoundError: No module named 'apiclient.discovery'

### ISSUE THREAD

**Issue by alphanumericaltycoon** [kindeep/redditVideoGenerator#16]
Hi,

Just trying to get this up and running. When I ran pip install -r requirements.txt there was a lot of red. So I installed as much as I can and I am now trying to run AskReddit.py and troubleshooting on the go.

My OS is Kali Linux. The current error when running AskReddit.py is:

``┌──(kali㉿kali)-[~/redditVideoGenerator]
└─$ python3 AskReddit.py                          
Traceback (most recent call last):
  File "/home/kali/redditVideoGenerator/AskReddit.py", line 4, in <module>
    from yt_upload import upload_video
  File "/home/kali/redditVideoGenerator/yt_upload.py", line 9, in <module>
    from apiclient.discovery import build
ModuleNotFoundError: No module named 'apiclient.discovery'
``

**Comment by Inthenew** [comment]
Just do pip3 install google-api-python-client
